# Dasar-dasar Operasi Tensor
## Mengimpor library pytorch

In [ ]:
import torch

## Membuat variabel

In [ ]:
# membuat variabel kosong dengan ukuran 2,4
emptyvar = torch.empty(2, 4)
# membuat variabel random dengan ukuran 2,3,4
randomvar = torch.rand(2, 3, 4)
# membuat variabel tensor dengan nilai 1 berukuran 2,3,4
onesvar = torch.ones(2, 3, 4)
# membuat variabel tensor dengan nilai 0 berukuran 4,5
zerosvar = torch.zeros(4, 5)
print(emptyvar, randomvar, onesvar, zerosvar)

## Membuat variabel tensor dengan tipe data spesifik

In [ ]:
# membuat tensor dengan tipe data integer
intvar = torch.ones(2, 2, dtype=torch.int)
# membuat tensor dengan tipe data float
floatvar = torch.rand(2, 2, dtype=torch.float)

print(intvar, floatvar)
print(intvar.dtype, floatvar.dtype)
print(intvar.size(), floatvar.size())

## Operasi Aritmatika Dasar pada Tensor

In [ ]:
# mengisi tensor dengan nilai
var_a = torch.tensor([[1, 2, 3], [4, 5, 6]])
# operasi aritmatika pada tensor
var_b = torch.tensor([[1, 2, 3], [4, 5, 6]])
var_c = var_a + var_b
print(var_c)

## Cara Lain Operasi Penjumlahan

In [ ]:
# cara lain
var_c = torch.add(var_a, var_b)
print(var_c)

# cara lain pada variabel yang sama
var_a.add_(var_b)
print(var_a)

## Operasi lainnya

In [ ]:
x = torch.rand(2, 2)
y = torch.rand(2, 2)

z_kali = x * y
z_kali_2 = torch.mul(x, y)

z_bagi = x / y
z_bagi_2 = torch.div(x, y)

z_pengurangan = x - y
z_pengurangan_2 = torch.sub(x, y)

z_pangkat = x ** y
z_pangkat_2 = torch.pow(x, y)

## Manipulasi Matriks

In [ ]:
x = torch.rand(5, 3)
print(x)
print(x[:, 0])  # mencetak hanya kolom pertama
print(x[0, :])  # mencetak hanya baris pertama
print(x[1, 1])  # mencetak nilai pada baris ke-1 dan kolom ke-1
print(x[1, 1].item())  # mencetak hanya nilai (tanpa identitas tensor)

## Reshaping Matriks
Mengubah matriks 2 dimensi menjadi array 1 dimensi

In [ ]:
x = torch.rand(4, 4)
print(x)
print(x.shape)
y = x.view(16)
print(y)
print(y.shape)

Cara lain untuk mentransformasikan matriks

In [ ]:
y = x.view(-1, 8)
print(y)
print(y.shape)

## Konversi dari Numpy ke Tensor

In [24]:
import numpy as np

a = torch.ones(5)
print(a)
b = a.numpy()
print(b)
print(type(b))

tensor([1., 1., 1., 1., 1.])
[1. 1. 1. 1. 1.]
<class 'numpy.ndarray'>


Perlu diperhatikan bahwa mengkonversi dari numpy ke tensor tidak membuat kopi, melainkan mengubah referensi dari numpy ke tensor.
Nilai b akan berubah ketika kita melakukan modifikasi terhadap nilai a.

In [25]:
a.add_(1)
print(a)
print(b)

tensor([2., 2., 2., 2., 2.])
[2. 2. 2. 2. 2.]


In [29]:
a = np.ones(5)
print(a)
b = torch.from_numpy(a)
print(b)

a = a + 1
print(a)
print(b)
print(type(b))

[1. 1. 1. 1. 1.]
tensor([1., 1., 1., 1., 1.], dtype=torch.float64)
[2. 2. 2. 2. 2.]
tensor([1., 1., 1., 1., 1.], dtype=torch.float64)
<class 'torch.Tensor'>


# Operasi Menggunakan GPU

In [ ]:
if torch.cuda.is_available():
    # Mengatur nama device sebagai variabel
    device = torch.device("cuda")
    # Membuat variabel tensor yang menggunakan device
    x = torch.ones(5, device=device)

    # Memindahkan variable yang sudah dibuat sebelumnya ke device
    y = torch.ones(5)
    y = y.to(device)

    # Memindahkan kembali ke CPU
    x = x.to("cpu")

# Mengaktifkan Variabel dengan Autograd

In [30]:
x = torch.ones(2, 2, requires_grad=True)
print(x)

tensor([[1., 1.],
        [1., 1.]], requires_grad=True)
